version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "mysql://root:root_password@db:3306/app_db"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migration # migrationステージを使う
    environment:
      DATABASE_URL: "mysql://root:root_password@db:3306/app_db"
    depends_on:
      db:
        condition: service_healthy
    command: ["npx", "prisma", "migrate", "deploy"]
  db:
    image: mysql:8.0.39
    platform: linux/amd64
    container_name: easytodo_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 3s
      start_period: 30s
      retries: 10
